---
title: "KNN Depression"
author: "Andrea Demelas"
date: "2026-04-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# import data

```{r}
depression <- readRDS("cleaned_depression.rds")
```


# training testing split original data structure (no dummy)

```{r}

ratio <- 0.5

train_rows_og <- sample(1:nrow(depression), ratio*nrow(depression))

train_og <- depression[train_rows_og, ]
test_og <- depression[-train_rows_og, ]

saveRDS(train_og, file = "train_original.rds")
saveRDS(test_og, file = "test_original.rds")

```


# training testing split dummy

```{r}

depression_d <- as.data.frame(model.matrix(~ . -1, data = depression))

library(janitor)

depression_d <- clean_names(depression_d)

str(depression_d)

minmax <- function(x){
  (x - min(x)) / (max(x) - min(x))
}

#normalized data
depression_n <- as.data.frame(lapply(depression_d, minmax))
```

## creating the clean training and testing data with dummy variables 

```{r}
set.seed(12345)
ratio <- 0.5

train_rows_dummy <- sample(1:nrow(depression_n), ratio*nrow(depression_n))

train_dummy <- depression_n[train_rows_dummy, ]
test_dummy <- depression_n[-train_rows_dummy, ]

saveRDS(train_dummy, file = "train_dummy.rds")
saveRDS(test_dummy, file = "test_dummy.rds")


```

# Load Data

```{r, cache = TRUE}
train_dummy <- readRDS("train_dummy.rds")
test_dummy  <- readRDS("test_dummy.rds")
```

# KNN Model on history of mental illness

```{r, cache = TRUE}
library(class)
library(caret)

knnpred_mental <- knn(train = train_dummy[, -(ncol(train_dummy)-3)],
                      test  = test_dummy[, -(ncol(test_dummy)-3)],
                      cl    = factor(train_dummy[, ncol(train_dummy)-3]),
                      k = 15, prob = TRUE)

p_mental <- attr(knnpred_mental, "prob")
knn_prob_mental <- ifelse(as.character(knnpred_mental) == 1, p_mental, 1 - p_mental)
summary(knn_prob_mental)
```

## Confusion Matrix

```{r, cache = TRUE}
confusionMatrix(as.factor(knnpred_mental),
                as.factor(test_dummy[, ncol(test_dummy)-3]),
                positive = "1")
```

# KNN Model on history of substance abuse

```{r, cache = TRUE}
knnpred_substance <- knn(train = train_dummy[, -(ncol(train_dummy)-2)],
                         test  = test_dummy[, -(ncol(test_dummy)-2)],
                         cl    = factor(train_dummy[, ncol(train_dummy)-2]),
                         k = 15, prob = TRUE)

p_substance <- attr(knnpred_substance, "prob")
knn_prob_substance <- ifelse(as.character(knnpred_substance) == 1, p_substance, 1 - p_substance)
summary(knn_prob_substance)
```

## Confusion Matrix

```{r, cache = TRUE}
confusionMatrix(as.factor(knnpred_substance),
                as.factor(test_dummy[, ncol(test_dummy)-2]),
                positive = "1")
```


# Save Probabilities

```{r, cache = TRUE}
saveRDS(knn_prob_mental, "knn_prob_mental_illness.rds")
saveRDS(knnpred_mental, "knn_pred_mental_illness.rds")

saveRDS(knn_prob_substance, "knn_prob_substance_abuse.rds")
saveRDS(knnpred_substance, "knn_pred_substance_abuse.rds")
```

